urls = (
    '/', 'application.controllers.main.index.Index',
    '/404', 'application.controllers.main.notfound.NotFound',
    '/500', 'application.controllers.main.internalerror.InternalError',
    "/login", "application.controllers.main.login.Login",
    "/loginselection", "application.controllers.main.loginselection.LoginSelection",
    "/logout", "application.controllers.main.logout.Logout",
    "/auth/(google)", "application.controllers.main.login.AuthPage",
    "/auth/(google)/callback", "application.controllers.main.login.AuthCallbackPage",
    '/users', 'application.controllers.users.index.Index',
    '/users/printer', 'application.controllers.users.printer.Printer',
    '/users/view/(.+)', 'application.controllers.users.view.View',
    '/users/edit/(.+)', 'application.controllers.users.edit.Edit',
    '/users/delete/(.+)', 'application.controllers.users.delete.Delete',
    '/users/insert', 'application.controllers.users.insert.Insert',
    '/users/csv_import', 'application.controllers.users.csv_import.CsvImport',
    '/logs', 'application.controllers.logs.index.Index',
    '/logs/printer', 'application.controllers.logs.printer.Printer',
    '/logs/view/(.+)', 'application.controllers.logs.view.View',

    '/paradas', 'application.controllers.paradas.index.Index',
    '/paradas/view/(.+)', 'application.controllers.paradas.view.View',
    '/paradas/edit/(.+)', 'application.controllers.paradas.edit.Edit',
    '/paradas/delete/(.+)', 'application.controllers.paradas.delete.Delete',
    '/paradas/insert', 'application.controllers.paradas.insert.Insert',
    '/rutas', 'application.controllers.rutas.index.Index',
    '/rutas/view/(.+)', 'application.controllers.rutas.view.View',
    '/rutas/edit/(.+)', 'application.controllers.rutas.edit.Edit',
    '/rutas/delete/(.+)', 'application.controllers.rutas.delete.Delete',
    '/rutas/insert', 'application.controllers.rutas.insert.Insert',
    '/tarifas', 'application.controllers.tarifas.index.Index',
    '/tarifas/view/(.+)', 'application.controllers.tarifas.view.View',
    '/tarifas/edit/(.+)', 'application.controllers.tarifas.edit.Edit',
    '/tarifas/delete/(.+)', 'application.controllers.tarifas.delete.Delete',
    '/tarifas/insert', 'application.controllers.tarifas.insert.Insert',
   )